### ISSUE TITLE
How do I keep conda-forge from building for python 3.12 ?

### ISSUE THREAD

**Issue by Didou09** [conda-forge/tofu-feedstock#58]
### Comment:

Hi,

I'm the maintainer of this package.

It has a compiled part, hence the use of things like `Cython`, `gcc`, `numpy` etc

Up to version `tofu 1.8.1`, the `conda-forge/tofu-feedstock` was building for python `3.9`, `3.10` and `3.11`, which was great.

https://anaconda.org/conda-forge/tofu

Since recently, `numpy 2` was released and now `conda-forge` wants to build against `python 3.12` all the time.

But my package is not ready for `numpy 2` and `python 3.12`.

How do  I tell the receipe to keep building for `numpy < 2` and python `3.9`, `3.10` and `3.11` until I get ready to move on to `numpy 2`?

I've tried multiple things, but the best so far as been to use Jinja tricks to specify a range of acceptable python versions in the recipe:

```
{% set name = "tofu" %}
{% set version = "1.8.4" %}
{% set python_min = "3.8" %}
{% set python_max = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f949640116f87aecd4d7aeee048b67ae4bc48d61421fd582ed83e5e2f2cd129f
  
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tofu-version = scripts.tofuversion:main
    - tofu-custom=scripts.tofucustom:main
    - tofu = scripts.tofu_bash:main

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >={{ python_min }},<={{ python_max }}
    - pip
    - cython => 0.26
    - numpy
    - setuptools >=40.8.0,<64
    - llvm-openmp  # [unix and not osx]
  run:
    - python >={{ python_min }},<={{ python_max }}
    - numpy
    - scipy
    - matplotlib-base
    - llvm-openmp  # [unix and not osx]
    - _openmp_mutex  # [unix and not osx]
    - requests
    - svg.path
    - Polygon3
    - spectrally >=0.0.7

test:
  imports:
    - tofu
    - tofu.geom
  commands:
    # - pytest tofu/tests
    - echo ""
  requires:
    - pytest
    - python >={{ python_min }},<={{ python_max }}
  source_files:
    - tofu/tests

about:
  home: https://github.com/ToFuProject/tofu
  license: MIT
  license_file: LICENSE.txt
  summary: Project for an open-source python library for synthetic diagnostics and tomography for Fusion devices.
  description: |
    tofu stands for Tomography for Fusion, it is an IMAS-compatible open-source
    machine-independent python library with non-open source plugins containing all machine-dependent routines.
    It aims at providing the fusion and plasma community with an object-oriented, transparent and documented tool
    for designing tomography diagnostics, computing synthetic signal (direct problem) as well as tomographic
    inversions (inverse problem). It gives access to a full 3D description of the diagnostic geometry, thus reducing
    the impact of geometrical approximations on the direct and, most importantly, on the inverse problem.
    tofu is relevant for all diagnostics integrating, in a finitie field of view or along a set of lines of sight,
    a quantity (scalar or vector) for which the plasma can be considered transparent (e.g.: light in the visible, UV,
    soft and hard X-ray ranges, or electron density for interferometers).

    tofu is command-line oriented, for maximum flexibility and scriptability. The absence of a GUI is compensated by
    built-in one-liners for interactive plots.

    A sphinx-generated documentation and the code itself is hosted on GitHub.
  doc_url: https://tofuproject.github.io/tofu/
  dev_url: https://github.com/ToFuProject/tofu

extra:
  recipe-maintainers:
    - flothesof
    - Didou09
    - lasofivec
```

But that gets the linter to complain that `noarch` recipes should not have python version specifiers.
How do I do this in a cleaner way ?

I've read about selector but apparently `noarch` also doesn't want to hear about it.

```
- build
    - skip # [py<312]
```
